name: Replace Repo Content

on:
  workflow_dispatch:

jobs:
  replace-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Clone target repository to temp directory
      run: git clone https://SvenWind97@dev.azure.com/SvenWind97/PHP%20NetRunner/_git/PNetRunner temp-repo

    - name: Create or update .gitignore to exclude azure-pipelines.yaml
      run: |
        echo "azure-pipelines.yaml" >> .gitignore
        git add .gitignore

    - name: Remove existing content
      run: git rm -rf . --ignore-unmatch

    - name: Copy new content, including hidden files
      run: cp -r temp-repo/. .

    - name: Configure GitHub authentication
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'SvenWind97@gmail.com'
        git remote remove origin
        git remote add origin https://github.com/SHW511/PHP-NetRunner.git

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Replace repository content with new content"
        git push https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/SHW511/PHP-NetRunner.git master --force
